### PR TITLE
Fix empty multistatus content

### LINKED ISSUE #218: Error: Invalid response: No root multistatus found
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns" />

```

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #218

cc @perry-mitchell @juliushaertl @christophwurst

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

File: source/interface/dav.js [hunk 1]
```diff
@@ -21,6 +21,13 @@ function normaliseResponse(response) {
 
 function normaliseResult(result) {
     const { multistatus } = result;
+    if (multistatus === '') {
```
Comment (perry-mitchell) [inline source/interface/dav.js:24]: Would this be better as a `!multistatus` check? This would catch occurences where `multistatus` might not be returned at all..

**Review by perry-mitchell — CHANGES_REQUESTED** [review]

File: source/interface/dav.js (hunk 1 above)
Comment (skjnldsv) [reply source/interface/dav.js:24]: well, it is bellow :)

Comment (skjnldsv) [reply source/interface/dav.js:24]: But bellow it throw, which is not good for empty multistatus. :thinking:

**Review by perry-mitchell — APPROVED** [review]

**Comment by skjnldsv** [comment]
Thanks a lot @perry-mitchell !
Love your lib :)

**Comment by emansom** [comment]
Great job, my savior! Is this merge included in latest Nextcloud?
